"""
BlenderNanoBanana - UV Atlas Compositor

Takes:
  - Per-tag seamless textures (generated by Gemini Image API)
  - UV island data including exact UV polygon coordinates
  - Island → tag mapping

Produces:
  - A single UV atlas image per PBR map type, where each UV island
    is filled with the appropriate material texture for that region.

This is standard game-dev workflow:
  1. Generate seamless textures per material (fast, minimal API calls)
  2. Composite into a UV atlas using island UV polygon masks (PIL only, no API)
  3. Apply ONE texture to the mesh — UV mapping handles the rest

No additional Gemini calls are made in this step.
"""

import io
import base64
from typing import Dict, List, Optional, Tuple
from ..utils.logging import log_info, log_debug, log_error

_MODULE = "UVCompositor"


def composite_uv_atlas(
    tag_images_b64: Dict[str, str],      # tag_name → base64 PNG/JPEG
    island_data: List[Dict],             # from nb_uv_analysis["islands"]
    island_tags: Dict[str, str],         # island_id → tag_name
    atlas_size: int = 2048,
    default_tag: Optional[str] = None,  # tag to use for untagged islands
) -> Optional[bytes]:
    """
    Composite multiple per-material seamless textures into a single UV atlas.

    Each UV island polygon is used as a mask. The corresponding material
    texture is tiled into the atlas at those UV coordinates.

    Returns PNG bytes of the atlas, or None on failure.
    """
    try:
        from PIL import Image, ImageDraw
    except ImportError:
        log_error("Pillow not installed — UV compositing unavailable.", _MODULE)
        return None

    if not island_data or not tag_images_b64:
        return None

    # Decode all per-tag textures once (shared across islands of same tag)
    tag_textures: Dict[str, Image.Image] = {}
    for tag, b64_str in tag_images_b64.items():
        try:
            raw = base64.b64decode(b64_str)
            img = Image.open(io.BytesIO(raw)).convert("RGBA")
            tag_textures[tag] = img
            log_debug(f"Loaded texture for tag '{tag}': {img.size}", _MODULE)
        except Exception as e:
            log_error(f"Could not decode texture for tag '{tag}': {e}", _MODULE)

    if not tag_textures:
        return None

    # Start with transparent atlas
    atlas = Image.new("RGBA", (atlas_size, atlas_size), (0, 0, 0, 0))

    painted_islands = 0

    for island in island_data:
        iid = island.get("id", "?")
        tag = island_tags.get(iid, default_tag)

        if not tag or tag not in tag_textures:
            # Untagged island — use the first available texture as fallback
            tag = next(iter(tag_textures), None)
            if not tag:
                continue

        tex = tag_textures[tag]
        face_polygons = island.get("face_polygons", [])
        if not face_polygons:
            continue

        # Step 1: Build a pixel-space mask for this island (union of all face polygons)
        mask = Image.new("L", (atlas_size, atlas_size), 0)
        mask_draw = ImageDraw.Draw(mask)
        for poly in face_polygons:
            # UV (u, v) → pixel (x, y): Y axis is flipped in image space
            px_coords = [
                (int(u * atlas_size), int((1.0 - v) * atlas_size))
                for u, v in poly
            ]
            if len(px_coords) >= 3:
                mask_draw.polygon(px_coords, fill=255)

        # Step 2: Tile the material texture across the full atlas
        # (seamless textures tile correctly — UV wrapping handles alignment)
        tiled = _tile_to_size(tex, atlas_size, atlas_size)

        # Step 3: Composite: paste tiled texture where mask is white
        atlas.paste(tiled, (0, 0), mask)
        painted_islands += 1

    log_info(f"Composited {painted_islands}/{len(island_data)} UV islands into atlas.", _MODULE)

    # Return as PNG bytes
    buf = io.BytesIO()
    atlas.save(buf, format="PNG")
    return buf.getvalue()


def composite_all_maps(
    tag_map_images_b64: Dict[str, Dict[str, str]],  # tag → {map_name → b64}
    island_data: List[Dict],
    island_tags: Dict[str, str],
    atlas_size: int = 2048,
) -> Dict[str, bytes]:
    """
    Composite a full PBR set (albedo, normal, roughness, ...) into UV atlases.

    Args:
        tag_map_images_b64: {tag_name: {map_name: base64_str}, ...}
        island_data: UV island list from nb_uv_analysis
        island_tags: island_id → tag_name
        atlas_size: output atlas resolution

    Returns:
        {map_name: png_bytes} — one atlas per PBR map type
    """
    # Collect all unique map names across all tags
    all_map_names = set()
    for maps in tag_map_images_b64.values():
        all_map_names.update(maps.keys())

    results: Dict[str, bytes] = {}

    for map_name in all_map_names:
        # Slice: for this map type, get {tag → b64}
        tag_images = {
            tag: maps[map_name]
            for tag, maps in tag_map_images_b64.items()
            if map_name in maps
        }

        if not tag_images:
            continue

        atlas_bytes = composite_uv_atlas(
            tag_images_b64=tag_images,
            island_data=island_data,
            island_tags=island_tags,
            atlas_size=atlas_size,
        )

        if atlas_bytes:
            results[map_name] = atlas_bytes
            log_info(f"Atlas created: {map_name} ({atlas_size}×{atlas_size})", _MODULE)

    return results


# ── Internal helpers ───────────────────────────────────────────────────────────

def _tile_to_size(tex: "Image.Image", width: int, height: int) -> "Image.Image":
    """
    Tile a seamless texture to fill an (width × height) canvas.
    """
    from PIL import Image
    tw, th = tex.size
    canvas = Image.new("RGBA", (width, height))
    for y in range(0, height, th):
        for x in range(0, width, tw):
            canvas.paste(tex, (x, y))
    return canvas
